/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentEventType = "booked" | "cancelled" | "completed" | "no_show" | "rescheduled";

export type AppointmentStatus = "cancelled" | "completed" | "no_show" | "scheduled";

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthAuthorizationStatus = "approved" | "denied" | "expired" | "pending";

export type AuthOauthClientType = "confidential" | "public";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOauthResponseType = "code";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type BlindPackageFamily = "combi" | "roller" | "roman_200" | "venetian_roman_non_200";

export type CurtainCategory = "Day" | "Night";

export type CurtainPackageDayGroup = "essential" | "none" | "signature";

export type CurtainProductLine = "blind" | "curtain";

export type CurtainTypeStatus = "Active" | "Archived";

export type DrawDirection = "Double" | "Single Left" | "Single Right";

export type FreightMode = "air" | "sea";

export type FulfilmentArrangementEventType = "booked" | "cancelled" | "rescheduled";

export type FulfilmentStatus = "completed" | "delivered_checked" | "deposit_received" | "fulfilment" | "order_recorded" | "po_ready" | "quotation_sent" | "sent_logistic" | "sent_to_vendor" | "shipping_sg";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GoogleSyncState = "failed" | "pending" | "synced";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InteractionType = "Appointment" | "Customer Message" | "Follow-Up" | "Note" | "Payment" | "Quote" | "Reply";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadClosureReason = "Communication / Poor Fit" | "Competitor" | "Ghosted" | "Other" | "Outside Scope" | "Price / Budget" | "Product Mismatch" | "Small Order / Low Value" | "Timing / No Longer Needed";

export type LeadContactChannel = "Other" | "Telegram" | "WhatsApp";

export type LeadDirection = "Inbound" | "Outbound";

export type LeadFunnelStage = "Activate Lead – Short Term" | "Attend Appointment" | "Book Appointment" | "Collect Deposit" | "Decision Pending" | "Lost" | "Not Qualified" | "Nurture Lead – Long Term" | "Qualify Lead" | "Send Quotation" | "Won";

export type LeadFunnelStageLegacy = "Appointment Booked" | "Decision Pending" | "Lost" | "New Lead" | "Not Qualified" | "Nurture" | "Post-Appointment / Quote Pending" | "Qualified / Pre-Appointment" | "Quote Sent" | "Won";

export type LeadOutcome = "Appointment Booked" | "Awaiting Customer" | "Customer Confirmed" | "Customer Declined" | "Customer Replied" | "No Response" | "Post-Appointment Barrier" | "Pre-Appointment Barrier" | "Quotation Sent";

export type LeadOutcomeLegacy = "Appointment Booked" | "Appointment Completed" | "Appointment Confirmed" | "Barrier / Objection Raised" | "Customer Declined" | "Customer Needs Time" | "Customer Replied" | "Follow-Up Sent" | "No Response" | "Order Confirmed" | "Quote Requested" | "Quote Sent" | "Ready to Book Appointment" | "Renovation Delayed";

export type LeadPrimaryProduct = "Both" | "Curtains / Blinds" | "Mesh";

export type LeadSource = "Carousell" | "Existing Customer" | "Organic" | "Other" | "Referral" | "SEM" | "Telegram Group Buy";

export type LeadStatus = "Active" | "Closed – Lost" | "Closed – Not Qualified" | "Closed – Won" | "Unresponsive";

export type LeadStatusLegacy = "Active" | "Ignore" | "Lost" | "Nurture" | "Unresponsive" | "Won";

export type MeshDrawDirection = "Double" | "Single Bottom" | "Single Left" | "Single Right" | "Single Top";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PricingAddonAutoRule = "always" | "manual" | "width_over";

export type PricingAddonBasis = "per_metre" | "per_unit";

export type PricingAddonScope = "blind" | "both" | "curtain";

export type PricingCalcMethod = "by_sqm" | "by_width";

export type ProductLine = "curtain" | "mesh";

export type PropertyType = "Commercial" | "Condo" | "HDB" | "Landed";

export type RoomType = "Balcony" | "Bedroom" | "Common Toilet" | "Kitchen" | "Living Room" | "Master Bedroom" | "Master Toilet" | "Other" | "Service Yard" | "Study Room";

export type SalesChannel = "carousell" | "standard";

export type StorageBuckettype = "ANALYTICS" | "STANDARD" | "VECTOR";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "consultant" | "ops";

export interface AppointmentEvents {
  appointment_id: string;
  created_by: string | null;
  event_type: AppointmentEventType;
  id: Generated<string>;
  is_backfilled: Generated<boolean>;
  lead_id: string;
  occurred_at: Generated<Timestamp>;
  previous_scheduled_at: Timestamp | null;
  scheduled_at: Timestamp | null;
}

export interface Appointments {
  address: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  development: string | null;
  duration_mins: Generated<number>;
  google_event_id: string | null;
  google_sync_error: string | null;
  google_sync_state: Generated<GoogleSyncState>;
  id: Generated<string>;
  lead_action_date_before: Timestamp | null;
  lead_id: string;
  lead_outcome_before: LeadOutcome | null;
  lead_stage_before: LeadFunnelStage | null;
  notes: string | null;
  scheduled_at: Timestamp;
  status: Generated<AppointmentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthCustomOauthProviders {
  acceptable_client_ids: Generated<string[]>;
  attribute_mapping: Generated<Json>;
  authorization_params: Generated<Json>;
  authorization_url: string | null;
  cached_discovery: Json | null;
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  custom_claims_allowlist: Generated<string[]>;
  discovery_cached_at: Timestamp | null;
  discovery_url: string | null;
  email_optional: Generated<boolean>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  identifier: string;
  issuer: string | null;
  jwks_uri: string | null;
  name: string;
  pkce_enabled: Generated<boolean>;
  provider_type: string;
  scopes: Generated<string[]>;
  skip_nonce_check: Generated<boolean>;
  token_url: string | null;
  updated_at: Generated<Timestamp>;
  userinfo_url: string | null;
}

export interface AuthFlowState {
  auth_code: string | null;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Timestamp | null;
  email_optional: Generated<boolean>;
  id: string;
  invite_token: string | null;
  linking_target_id: string | null;
  oauth_client_state_id: string | null;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  referrer: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  last_webauthn_challenge_data: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthAuthorizations {
  approved_at: Timestamp | null;
  authorization_code: string | null;
  authorization_id: string;
  client_id: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirect_uri: string;
  resource: string | null;
  response_type: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  user_id: string | null;
}

export interface AuthOauthClients {
  client_name: string | null;
  client_secret_hash: string | null;
  client_type: Generated<AuthOauthClientType>;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  token_endpoint_auth_method: string;
  updated_at: Generated<Timestamp>;
}

export interface AuthOauthClientStates {
  code_verifier: string | null;
  created_at: Timestamp;
  id: string;
  provider_type: string;
}

export interface AuthOauthConsents {
  client_id: string;
  granted_at: Generated<Timestamp>;
  id: string;
  revoked_at: Timestamp | null;
  scopes: string;
  user_id: string;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  oauth_client_id: string | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refresh_token_counter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refresh_token_hmac_key: string | null;
  refreshed_at: Timestamp | null;
  scopes: string | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface AuthWebauthnChallenges {
  challenge_type: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  session_data: Json;
  user_id: string | null;
}

export interface AuthWebauthnCredentials {
  aaguid: string | null;
  attestation_type: Generated<string>;
  backed_up: Generated<boolean>;
  backup_eligible: Generated<boolean>;
  created_at: Generated<Timestamp>;
  credential_id: Buffer;
  friendly_name: Generated<string>;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  public_key: Buffer;
  sign_count: Generated<Int8>;
  transports: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface BlindPackagePrices {
  family: BlindPackageFamily;
  price_sgd_cents: number | null;
  property_tier_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CurtainPackagePricesLegacy {
  essential_price_sgd_cents: number | null;
  pls_upgrade_sgd_cents: number | null;
  property_tier_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CurtainPackages {
  base_tier: Generated<string>;
  created_at: Generated<Timestamp>;
  day_group: CurtainPackageDayGroup | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  night_group: string | null;
  package_type: Generated<string>;
  price_sgd_cents: number;
  property_tier_id: string;
  room_tier2_downgrade_sgd_cents: number | null;
  room_tier2_upgrade_sgd_cents: number | null;
  tier2_upgrade_sgd_cents: number | null;
  updated_at: Generated<Timestamp>;
}

export interface CurtainPricingAdjustments {
  add_day_sgd_cents: number;
  add_essential_sgd_cents: number;
  add_pls_sgd_cents: number;
  blackout_per_m_sgd_cents: number;
  remove_day_sgd_cents: number;
  remove_essential_sgd_cents: number;
  remove_pls_sgd_cents: number;
  s_fold_3m_sgd_cents: number;
  s_fold_4m_sgd_cents: number;
  s_fold_above_4m_sgd_cents: number | null;
  singleton: Generated<boolean>;
  slim_double_per_m_sgd_cents: number;
  slim_single_per_m_sgd_cents: number;
  ultimate_from_essential_sgd_cents: number;
  ultimate_from_pls_sgd_cents: number;
  updated_at: Generated<Timestamp>;
  zen_4m_sgd_cents: number;
  zen_5m_sgd_cents: number;
  zen_default_sgd_cents: number;
}

export interface CurtainSeries {
  calc_method: Generated<PricingCalcMethod>;
  cost_rmb_cents: number | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  name_cn: string | null;
  product_line: Generated<CurtainProductLine>;
  sale_sgd_cents: number | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string | null;
}

export interface CurtainTypes {
  category: CurtainCategory | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  label: string;
  page: string | null;
  photo_mime: string | null;
  photo_path: string | null;
  series_id: string | null;
  series_index: number | null;
  status: Generated<CurtainTypeStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Customers {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  email: string | null;
  id: Generated<string>;
  mobile: string;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DeliveryVendors {
  address_cn: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_default: Generated<boolean>;
  label: string;
  phone: string | null;
  recipient_cn: string | null;
  shipping_mark_cn: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface FulfilmentArrangementEvents {
  address: string;
  arrangement_id: string;
  cancellation_reason: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  duration_mins: number;
  event_type: FulfilmentArrangementEventType;
  id: Generated<string>;
  scheduled_at: Timestamp;
}

export interface FulfilmentArrangements {
  address: string;
  cancellation_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  duration_mins: Generated<number>;
  google_event_id: string | null;
  google_sync_error: string | null;
  google_sync_state: Generated<GoogleSyncState>;
  id: Generated<string>;
  order_id: string;
  scheduled_at: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface LeadImportBaselines {
  as_of: Timestamp;
  last_contact_at: Timestamp | null;
  last_customer_response_at: Timestamp | null;
  last_message_by: LeadDirection | null;
  lead_id: string;
  unanswered_followups: number;
}

export interface LeadInteractions {
  channel: LeadContactChannel | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  direction: LeadDirection | null;
  id: Generated<string>;
  interaction_type: InteractionType;
  lead_id: string;
  note: string | null;
  occurred_at: Timestamp;
}

export interface LeadLegacyImport {
  action_date: Timestamp | null;
  action_detail_override: string | null;
  buying_readiness: string | null;
  expected_key_date: string | null;
  first_initiated_at: Timestamp | null;
  funnel_stage: LeadFunnelStageLegacy;
  keys_status: string | null;
  last_contact_at: Timestamp | null;
  last_customer_response_at: Timestamp | null;
  last_outcome: LeadOutcomeLegacy | null;
  lead_id: string;
  lead_status: LeadStatusLegacy;
  owner_id: string | null;
  snapshot_at: Generated<Timestamp>;
}

export interface Leads {
  action_detail: string | null;
  assigned_consultant_id: string | null;
  closure_reason: LeadClosureReason | null;
  contact_channel: LeadContactChannel;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  development: string | null;
  dismissed_recommendations: Generated<string[]>;
  first_initiated_at: Timestamp | null;
  funnel_stage: Generated<LeadFunnelStage>;
  historical_summary: string | null;
  id: Generated<string>;
  inbound_outbound: LeadDirection | null;
  interaction_summary: string | null;
  is_archived: Generated<boolean>;
  keys_collected: boolean | null;
  last_contact_at: Timestamp | null;
  last_customer_response_at: Timestamp | null;
  last_message_by: LeadDirection | null;
  last_outcome: LeadOutcome | null;
  latest_quote_cents: number | null;
  latest_quote_note: string | null;
  lead_ref: string;
  lead_status: LeadStatus;
  mobile: string | null;
  move_in_date: Timestamp | null;
  name: string;
  next_action_date: Timestamp | null;
  owner_id: string | null;
  primary_product: LeadPrimaryProduct | null;
  quotation_breakdown: string | null;
  quotation_sent_at: Timestamp | null;
  quote_valid_days: Generated<number>;
  source: LeadSource | null;
  source_ref: string | null;
  telegram_chat_id: string | null;
  unanswered_followups: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface LeadStageEvents {
  changed_at: Timestamp;
  changed_by: string | null;
  created_at: Generated<Timestamp>;
  from_stage: LeadFunnelStage | null;
  id: Generated<string>;
  lead_id: string;
  source: string;
  to_stage: LeadFunnelStage;
}

export interface ManufactureAllowances {
  height_delta_cm: number | null;
  product_line: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  width_delta_cm: number | null;
}

export interface ManufactureMeasurements {
  confirmed_at: Generated<Timestamp>;
  confirmed_by: string | null;
  height_delta_cm: number;
  id: Generated<string>;
  is_overridden: Generated<boolean>;
  mesh_panel_id: string | null;
  mfg_height_cm: number;
  mfg_width_cm: number;
  order_id: string;
  override_reason: string | null;
  source_height_cm: number;
  source_width_cm: number;
  updated_at: Generated<Timestamp>;
  width_delta_cm: number;
  window_id: string | null;
}

export interface ManufacturePos {
  category: string | null;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  id: Generated<string>;
  notes: string | null;
  order_id: string;
  po_number: string;
  storage_path: string;
  superseded_at: Timestamp | null;
  vendor_id: string | null;
}

export interface MeshCategories {
  cost_rmb_cents_per_sqft: number | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  position: Generated<number>;
  sale_sgd_cents_per_sqft: number | null;
  updated_at: Generated<Timestamp>;
  vendor_id: string | null;
}

export interface MeshColours {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  position: Generated<number>;
  surcharge_rmb_cents: number | null;
  surcharge_sgd_cents: number | null;
  updated_at: Generated<Timestamp>;
}

export interface MeshMinimumAreas {
  category_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  min_area_cm2_per_leaf: number;
  system_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MeshPanels {
  category_id: string | null;
  colour_id: string | null;
  created_at: Generated<Timestamp>;
  draw: MeshDrawDirection | null;
  has_inset_horizontal: Generated<boolean>;
  has_inset_vertical: Generated<boolean>;
  has_window: Generated<boolean>;
  height_cm: number | null;
  id: Generated<string>;
  notes: string | null;
  position: number;
  room_id: string;
  split_left_cm: number | null;
  split_right_cm: number | null;
  width_cm: number | null;
}

export interface MeshSystemBands {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  double_system: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_width_cm: number;
  position: Generated<number>;
  single_system: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MeshSystems {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  double_cost_rmb_cents: number | null;
  double_sale_sgd_cents: number | null;
  handle_mm: number;
  id: Generated<string>;
  inset_deduction_mm: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  position: Generated<number>;
  roller_mm: number;
  side_track_mm: number;
  track_depth_mm: number;
  track_height_mm: number;
  updated_at: Generated<Timestamp>;
}

export interface Orders {
  appointment_id: string | null;
  balance_cents: Generated<number | null>;
  channel: Generated<SalesChannel>;
  consultant_id: string | null;
  created_at: Generated<Timestamp>;
  current_status: Generated<FulfilmentStatus>;
  curtain_package_id: string | null;
  curtain_package_name: string | null;
  curtain_package_rules: Json | null;
  curtain_package_sale_sgd_cents: number | null;
  curtain_package_tier: string | null;
  curtain_package_type: string | null;
  customer_id: string;
  delivery_vendor_id: string | null;
  deposit_cents: Generated<number>;
  development: string | null;
  discount_bps: Generated<number>;
  display_id: string;
  extra_install_sgd_cents: Generated<number>;
  freight_mode: Generated<FreightMode>;
  general_notes: string | null;
  goods_local_delivery_number: string | null;
  goods_overseas_tracking_number: string | null;
  id: Generated<string>;
  is_draft: Generated<boolean>;
  lead_id: string | null;
  move_in_date: Timestamp | null;
  order_reference: string | null;
  po_customer_reference: string | null;
  price_calc_at_quote_cents: number | null;
  price_quoted_cents: Generated<number>;
  product_line: Generated<ProductLine>;
  promo_label: string | null;
  property_type: PropertyType | null;
  seq_num: number;
  seq_year: number;
  site_address: string | null;
  track_local_delivery_number: string | null;
  track_overseas_tracking_number: string | null;
  unit_type: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OrderStatusEvents {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  note: string | null;
  order_id: string;
  status: FulfilmentStatus;
}

export interface OrderYearCounters {
  last_seq: Generated<number>;
  year: number;
}

export interface PoOpeningLabels {
  draw: string;
  label_cn: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PoTypeLabels {
  key: string;
  label_cn: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PricingAddons {
  applies_to: Generated<PricingAddonScope>;
  auto_rule: Generated<PricingAddonAutoRule>;
  auto_width_over_cm: number | null;
  basis: Generated<PricingAddonBasis>;
  cost_rmb_cents: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  label: string;
  sale_sgd_cents: number | null;
  updated_at: Generated<Timestamp>;
}

export interface PricingAssumptions {
  air_freight_cap_rmb_cents: number;
  air_freight_floor_rmb_cents: number;
  air_freight_rate_bps: number;
  fx_sgd_to_rmb: number;
  groupbuy_discount_bps: number;
  gst_bps: number;
  handyman_blinds_sgd_cents: Generated<number>;
  handyman_double_sgd_cents: Generated<number>;
  handyman_mesh_sgd_cents: Generated<number>;
  handyman_single_sgd_cents: Generated<number>;
  min_margin_bps: number;
  min_margin_carousell_bps: number;
  other_cost_bps: number;
  sea_freight_rmb_cents_per_m3: number;
  singleton: Generated<boolean>;
  style_multiplier: number;
  track_cost_rmb_cents_per_m: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface PricingCombos {
  created_at: Generated<Timestamp>;
  day_series_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  night_series_id: string | null;
  price_sgd_cents: number;
  updated_at: Generated<Timestamp>;
}

export interface PricingPropertyTiers {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string;
  position: number;
  room_set_count: number;
  updated_at: Generated<Timestamp>;
}

export interface ProcurementSettings {
  address_line1: string;
  address_line2: string;
  air_shipping_mark: string | null;
  company_name: string;
  company_uen: string;
  curtain_style_cn: string | null;
  delivery_phone: string | null;
  floor_clearance_cm: number | null;
  heat_setting_cn: string | null;
  phone: string;
  recipient_cn: string | null;
  singleton: Generated<boolean>;
  track_note_cn: string | null;
  updated_at: Generated<Timestamp>;
  warehouse_address_cn: string | null;
  website: string;
  wechat: string;
}

export interface Profiles {
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string | null;
  id: string;
  is_active: Generated<boolean>;
  is_presales_owner: Generated<boolean>;
  role: Generated<UserRole>;
  updated_at: Generated<Timestamp>;
}

export interface Promotions {
  created_at: Generated<Timestamp>;
  discount_bps: number;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeMessages {
  binary_payload: Buffer | null;
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  action_filter: Generated<string | null>;
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  selected_columns: string[] | null;
  subscription_id: string;
}

export interface RoomPhotos {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mime_type: string;
  original_name: string | null;
  position: Generated<number>;
  room_id: string;
  size_bytes: number;
  storage_path: string;
  uploaded_by: string | null;
}

export interface Rooms {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
  order_id: string;
  position: number;
  type: RoomType;
}

export interface RoomTypeLabels {
  code: string;
  name_cn: string | null;
  room_type: RoomType;
  updated_at: Generated<Timestamp>;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp | null>;
  versioning_status: Generated<string>;
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  format: Generated<string>;
  id: Generated<string>;
  name: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageBucketsVectors {
  created_at: Generated<Timestamp>;
  id: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  archived_at: Timestamp | null;
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  is_delete_marker: Generated<boolean>;
  is_versioned: Generated<boolean>;
  last_accessed_at: Generated<Timestamp | null>;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  metadata: Json | null;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface StorageVectorIndexes {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  data_type: string;
  dimension: number;
  distance_metric: string;
  id: Generated<string>;
  metadata_configuration: Json | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface Vendors {
  address_cn: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  internal_ref: string | null;
  is_active: Generated<boolean>;
  name: string;
  name_cn: string | null;
  notes: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface WindowAddons {
  addon_id: string;
  created_at: Generated<Timestamp>;
  window_id: string;
}

export interface Windows {
  blind_type_id: string | null;
  combo_id: string | null;
  created_at: Generated<Timestamp>;
  day_curtain_type_id: string | null;
  draw: DrawDirection | null;
  height_cm: number | null;
  id: Generated<string>;
  night_curtain_type_id: string | null;
  notes: string | null;
  overlap_tracks_attachment: Generated<boolean>;
  position: number;
  room_id: string;
  side_installation: Generated<boolean>;
  split_left_cm: number | null;
  split_right_cm: number | null;
  width_cm: number | null;
}

export interface DB {
  appointment_events: AppointmentEvents;
  appointments: Appointments;
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.custom_oauth_providers": AuthCustomOauthProviders;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.oauth_authorizations": AuthOauthAuthorizations;
  "auth.oauth_client_states": AuthOauthClientStates;
  "auth.oauth_clients": AuthOauthClients;
  "auth.oauth_consents": AuthOauthConsents;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  "auth.webauthn_challenges": AuthWebauthnChallenges;
  "auth.webauthn_credentials": AuthWebauthnCredentials;
  blind_package_prices: BlindPackagePrices;
  curtain_package_prices_legacy: CurtainPackagePricesLegacy;
  curtain_packages: CurtainPackages;
  curtain_pricing_adjustments: CurtainPricingAdjustments;
  curtain_series: CurtainSeries;
  curtain_types: CurtainTypes;
  customers: Customers;
  delivery_vendors: DeliveryVendors;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  fulfilment_arrangement_events: FulfilmentArrangementEvents;
  fulfilment_arrangements: FulfilmentArrangements;
  lead_import_baselines: LeadImportBaselines;
  lead_interactions: LeadInteractions;
  lead_legacy_import: LeadLegacyImport;
  lead_stage_events: LeadStageEvents;
  leads: Leads;
  manufacture_allowances: ManufactureAllowances;
  manufacture_measurements: ManufactureMeasurements;
  manufacture_pos: ManufacturePos;
  mesh_categories: MeshCategories;
  mesh_colours: MeshColours;
  mesh_minimum_areas: MeshMinimumAreas;
  mesh_panels: MeshPanels;
  mesh_system_bands: MeshSystemBands;
  mesh_systems: MeshSystems;
  order_status_events: OrderStatusEvents;
  order_year_counters: OrderYearCounters;
  orders: Orders;
  po_opening_labels: PoOpeningLabels;
  po_type_labels: PoTypeLabels;
  pricing_addons: PricingAddons;
  pricing_assumptions: PricingAssumptions;
  pricing_combos: PricingCombos;
  pricing_property_tiers: PricingPropertyTiers;
  procurement_settings: ProcurementSettings;
  profiles: Profiles;
  promotions: Promotions;
  "realtime.messages": RealtimeMessages;
  "realtime.schema_migrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  room_photos: RoomPhotos;
  room_type_labels: RoomTypeLabels;
  rooms: Rooms;
  "storage.buckets": StorageBuckets;
  "storage.buckets_analytics": StorageBucketsAnalytics;
  "storage.buckets_vectors": StorageBucketsVectors;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.s3_multipart_uploads": StorageS3MultipartUploads;
  "storage.s3_multipart_uploads_parts": StorageS3MultipartUploadsParts;
  "storage.vector_indexes": StorageVectorIndexes;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
  vendors: Vendors;
  window_addons: WindowAddons;
  windows: Windows;
}
