import Link from "next/link";
import { sql } from "kysely";
import { requireRole } from "@/lib/auth/require-role";
import { db } from "@/lib/db/kysely";
import { CONTACT_CHANNELS, FUNNEL_STAGES, LEAD_SOURCES, LEAD_STATUSES, PRIMARY_PRODUCTS } from "@/lib/leads/funnel-types";
import { WorkView } from "@/components/leads/work-view";

export const dynamic = "force-dynamic";
export const metadata = { title: "Leads — Drapeworks CRM" };

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requireRole(["consultant", "admin"]);
  const p = await searchParams;
  const view = p.view === "all" ? "all" : "work";
  const tabs = <nav aria-label="Lead workspace views" className="inline-flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><Link href="/leads?view=work" className={`rounded-lg px-4 py-2 text-sm font-medium transition-colors ${view === "work" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:bg-slate-100 hover:text-slate-900"}`}>My Work</Link><Link href="/leads?view=all" className={`rounded-lg px-4 py-2 text-sm font-medium transition-colors ${view === "all" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:bg-slate-100 hover:text-slate-900"}`}>All Leads</Link></nav>;
  const toolbar = <div className="mb-6 flex items-center justify-between gap-3">{tabs}<Link className="inline-flex h-10 shrink-0 items-center justify-center rounded-lg bg-teal-600 px-4 text-sm font-medium text-white shadow-sm transition-colors hover:bg-teal-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2" href="/leads/new">New Lead</Link></div>;
  if (view === "work") return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8"><div className="mb-4"><h1 className="text-2xl font-bold">Leads</h1><p className="text-sm text-slate-500">Your prioritized sales workspace</p></div>{toolbar}<WorkView params={p} userId={session.user.id}/></main>;
  let q = db.selectFrom("leads")
    .leftJoin("profiles as consultant", "consultant.id", "leads.assigned_consultant_id")
    .select(["leads.id", "lead_ref", "name", "mobile", "funnel_stage", "lead_status", "last_outcome", "contact_channel", "source", "primary_product", "latest_quote_cents", "consultant.full_name as consultant_name", sql<string | null>`next_action_date::text`.as("next_action_date_text")])
    .where("is_archived", "=", false);
  if (p.q && p.q.length >= 2) q = q.where(eb => eb.or([eb("name", "ilike", `%${p.q}%`), eb("mobile", "ilike", `%${p.q}%`), eb("development", "ilike", `%${p.q}%`), eb("lead_ref", "ilike", `%${p.q}%`)]));
  if (FUNNEL_STAGES.includes(p.stage as never)) q = q.where("funnel_stage", "=", p.stage as never);
  if (LEAD_STATUSES.includes(p.status as never)) q = q.where("lead_status", "=", p.status as never);
  if (CONTACT_CHANNELS.includes(p.channel as never)) q = q.where("contact_channel", "=", p.channel as never);
  if (LEAD_SOURCES.includes(p.source as never)) q = q.where("source", "=", p.source as never);
  if (PRIMARY_PRODUCTS.includes(p.product as never)) q = q.where("primary_product", "=", p.product as never);
  if (p.needs_review === "1") q = q.where("move_in_date", "is", null).where(sql<boolean>`exists(select 1 from lead_legacy_import x where x.lead_id=leads.id and x.buying_readiness is not null)`);
  const total = (await q.clearSelect().select(sql<number>`count(*)::int`.as("count")).executeTakeFirstOrThrow()).count;
  const pageSize = 25;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const requestedPage = Number.parseInt(p.page ?? "1", 10);
  const page = Math.min(Math.max(Number.isFinite(requestedPage) ? requestedPage : 1, 1), pageCount);
  const rows = await q.orderBy("name").limit(pageSize).offset((page - 1) * pageSize).execute();
  const pageHref = (nextPage: number) => { const params = new URLSearchParams(Object.entries(p).filter((entry): entry is [string, string] => entry[1] !== undefined)); params.set("view", "all"); params.set("page", String(nextPage)); return `/leads?${params.toString()}`; };
  const select = (name: string, label: string, values: readonly string[]) => <select name={name} defaultValue={p[name] ?? ""} className="h-10 min-w-0 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100"><option value="">{label}</option>{values.map(value => <option key={value}>{value}</option>)}</select>;
  return <main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
    <div className="mb-4"><h1 className="text-2xl font-bold">Leads</h1><p className="text-sm text-slate-500">{total} matching records</p></div>
    {toolbar}
    <form className="mb-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><input type="hidden" name="view" value="all"/><div className="grid grid-cols-1 gap-3 p-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><input name="q" defaultValue={p.q} placeholder="Search leads" className="h-10 min-w-0 rounded-lg border border-slate-200 px-3 text-sm outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100"/>{select("stage", "All stages", FUNNEL_STAGES)}{select("status", "All statuses", LEAD_STATUSES)}{select("channel", "All channels", CONTACT_CHANNELS)}{select("source", "All sources", LEAD_SOURCES)}{select("product", "All products", PRIMARY_PRODUCTS)}</div><div className="flex flex-col gap-3 border-t border-slate-100 bg-slate-50/70 px-3 py-3 sm:flex-row sm:items-center sm:justify-end"><label className="flex h-10 items-center gap-2 text-sm text-slate-700"><input className="size-4 rounded border-slate-300 text-teal-600 focus:ring-teal-500" type="checkbox" name="needs_review" value="1" defaultChecked={p.needs_review === "1"}/>Needs review</label><button className="inline-flex h-10 w-full items-center justify-center rounded-lg bg-slate-900 px-5 text-sm font-medium text-white shadow-sm transition-colors hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-500 focus-visible:ring-offset-2 sm:w-auto">Apply filters</button></div></form>
    <div className="space-y-3 md:hidden">{rows.map(row => <article key={row.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Link className="font-semibold text-teal-700" href={`/leads/${row.id}`}>{row.name}</Link><div className="mt-0.5 text-xs text-slate-500">{row.lead_ref} · {row.contact_channel}</div></div>{row.latest_quote_cents ? <span className="shrink-0 text-sm font-semibold">${(row.latest_quote_cents / 100).toFixed(2)}</span> : null}</div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><div className="text-xs text-slate-500">Stage</div><div className="mt-0.5 font-medium">{row.funnel_stage}</div></div><div><div className="text-xs text-slate-500">Status</div><div className="mt-0.5 font-medium">{row.lead_status}</div></div><div><div className="text-xs text-slate-500">Outcome</div><div className="mt-0.5">{row.last_outcome ?? "—"}</div></div><div><div className="text-xs text-slate-500">Owner / next</div><div className="mt-0.5">{row.consultant_name ?? "Pre-sales"} · {row.next_action_date_text ?? "No date"}</div></div></div><Link href={`/leads/${row.id}`} className="mt-4 inline-flex h-10 w-full items-center justify-center rounded-lg border border-slate-200 text-sm font-medium text-slate-700 hover:bg-slate-50">View lead</Link></article>)}</div>
    <div className="hidden overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm md:block"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b bg-slate-50/70 text-left text-slate-600">{["Customer", "Stage", "Status", "Outcome", "Owner", "Channel", "Source", "Next action", "Quote"].map(label => <th className="p-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b last:border-b-0 hover:bg-slate-50/70"><td className="p-3"><Link className="font-medium text-teal-700" href={`/leads/${row.id}`}>{row.name}</Link><div className="text-xs text-slate-500">{row.lead_ref}</div></td><td className="p-3">{row.funnel_stage}</td><td className="p-3">{row.lead_status}</td><td className="p-3">{row.last_outcome ?? "—"}</td><td className="p-3">{row.consultant_name ?? "Pre-sales"}</td><td className="p-3">{row.contact_channel}</td><td className="p-3">{row.source ?? "—"}</td><td className="p-3">{row.next_action_date_text ?? "—"}</td><td className="p-3">{row.latest_quote_cents ? `$${(row.latest_quote_cents / 100).toFixed(2)}` : "—"}</td></tr>)}</tbody></table></div>
    <nav aria-label="Leads pagination" className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">Showing {total === 0 ? 0 : (page - 1) * pageSize + 1}–{Math.min(page * pageSize, total)} of {total}</p><div className="flex items-center gap-1"><Link aria-disabled={page === 1} tabIndex={page === 1 ? -1 : undefined} className={`inline-flex h-9 items-center justify-center rounded-lg border px-3 text-sm font-medium ${page === 1 ? "pointer-events-none border-slate-200 text-slate-300" : "border-slate-200 bg-white text-slate-700 hover:bg-slate-50"}`} href={pageHref(Math.max(1, page - 1))}>Previous</Link><span className="min-w-20 text-center text-sm text-slate-600">Page {page} of {pageCount}</span><Link aria-disabled={page === pageCount} tabIndex={page === pageCount ? -1 : undefined} className={`inline-flex h-9 items-center justify-center rounded-lg border px-3 text-sm font-medium ${page === pageCount ? "pointer-events-none border-slate-200 text-slate-300" : "border-slate-200 bg-white text-slate-700 hover:bg-slate-50"}`} href={pageHref(Math.min(pageCount, page + 1))}>Next</Link></div></nav>
  </main>;
}
